version: "3.8"
services:
  pet-project-database:
    container_name: pet-project-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: jhchoi1182/pet-project-database
    environment:
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - MYSQL_USER=jhchoi1182
      - MYSQL_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - MYSQL_DATABASE=pet-project
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  pet-project-app:
    container_name: pet-project-app
    build: .
    depends_on:
      - pet-project-database
    image: jhchoi1182/pet-project-app
    environment:
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_PW=${GOOGLE_CLIENT_PW}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    ports:
      - "8080:8080"
    restart: always
