spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  security:
    oauth2.client:
      registration:
        google:
          clientId: ${GOOGLE_CLIENT_ID}
          clientSecret: ${GOOGLE_CLIENT_PW}
          redirectUri: ${GOOGLE_REDIRECT_URI}
          scope:
            - email
            - profile
      provider:
        google:
          tokenUri: https://oauth2.googleapis.com/token
          userInfoUri: https://openidconnect.googleapis.com/v1/userinfo

jwt:
  secret-key: ${JWT_SECRET_KEY}
  token:
    expired-time-ms: 604800000

logging:
  level:
    org:
      springframework: debug

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/pet-project
    username: jhchoi1182
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false

pet-project:
  recommendation:
    base:
      url: http://localhost:8080/dir/

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://pet-project-database:3306/pet-project
    username: jhchoi1182
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true


pet-project:
  recommendation:
    base:
      url: https://jihyeon.store/dir/
