spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common
  datasource:
    url: jdbc:mysql://localhost:3306/pet-project
    username: jhchoi1182
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  token:
    expired-time-ms: 604800000

logging:
  level:
    org:
      springframework: info

---
spring:
  config:
    activate:
      on-profile: local

pet-project:
  recommendation:
    base:
      url: http://localhost:8080/dir/

---
spring:
  config:
    activate:
      on-profile: prod

pet-project:
  recommendation:
    base:
      url: https://jihyeon.store/dir/
