name: EC2 CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_ssh_key.pem
        chmod 600 ec2_ssh_key.pem

    - name: Update server code
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_ssh_key.pem ec2-user@${{ secrets.EC2_HOST }} "cd todo-server && git pull origin main"

    - name: Build project
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_ssh_key.pem ec2-user@${{ secrets.EC2_HOST }} "cd todo-server && ./gradlew clean build"

    - name: Rebuild and restart Docker containers
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_ssh_key.pem ec2-user@${{ secrets.EC2_HOST }} "cd todo-server && docker-compose up --build -d"

    - name: Prune Docker images
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_ssh_key.pem ec2-user@${{ secrets.EC2_HOST }} "docker image prune -f"
