name: EC2 CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_CMD: ssh -o StrictHostKeyChecking=no -i ec2_ssh_key.pem ec2-user@${{ secrets.EC2_HOST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_ssh_key.pem
          chmod 600 ec2_ssh_key.pem

      - name: Update server code
        run: ${{ env.SSH_CMD }} "cd todo-server && git pull origin main"

      - name: Build project
        run: ${{ env.SSH_CMD }} "cd todo-server && ./gradlew clean build"

      - name: Rebuild and restart Docker containers
        run: ${{ env.SSH_CMD }} "cd todo-server && docker-compose up --build -d"

      - name: Prune Docker images
        run: ${{ env.SSH_CMD }} "docker image prune -f"
