name: EC2 Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_ssh_key.pem
        chmod 600 ec2_ssh_key.pem

    - name: Connect to EC2 and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_ssh_key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd todo-server
          git pull origin main
          ./gradlew clean build
          docker-compose up --build -d
          docker image prune -f
        EOF
